#ifndef INC_NMEA_CONFIG_H_
#define INC_NMEA_CONFIG_H_

#define SENTENCE_AAM_ENABLED true
#define SENTENCE_ABK_ENABLED true
#define SENTENCE_ABM_ENABLED true
#define SENTENCE_ACA_ENABLED true
#define SENTENCE_ACK_ENABLED true
#define SENTENCE_ACN_ENABLED true
#define SENTENCE_ACS_ENABLED true
#define SENTENCE_AIR_ENABLED true
#define SENTENCE_AKD_ENABLED true
#define SENTENCE_ALA_ENABLED true
#define SENTENCE_ALC_ENABLED true
#define SENTNECE_ALF_ENABLED true

#endif
